Map<dynamic, dynamic> valueOfPlayer = new Map();
Map<dynamic, dynamic> playerTeamCode = new Map();
Map<dynamic, dynamic> playerPositionCode = new Map();
Map<dynamic,dynamic>goals=new Map();
Map<dynamic,dynamic>assists=new Map();
Map<dynamic,dynamic>price=new Map();
Map<dynamic,dynamic>rank=new Map();
Map<dynamic,dynamic>positionName=new Map();
Map<dynamic,dynamic>totalPoints = new Map();